const NavigationRoutes = {
  BOTTOMSTACK: 'BOTTOMSTACK',
  HOMESTACK: 'HOMESTACK',
  HOME: 'HOME',
  SEARCHSTACK: 'SEARCHSTACK',
  FOLDERSTACK: 'FOLDERSTACK',
  PROFILESTACK: 'PROFILESTACK',
  SETTINGSTACK: 'SETTINGSTACK'
};

export default NavigationRoutes;
